library(survminer)

ggsurvplot(survfit(se ~ 1, dtmin), dtmin)
ggsave("figures/overall.png")
ggsurvplot(survfit(se ~ sex, dtmin), dtmin, pval = TRUE, pval.coord = c(150, 0.10), pval.size = 4) + ggtitle("Survival by sex") + xlab("Time (months)")
ggsave("figures/sex.png")
ggsurvplot(survfit(se ~ sirs, dtmin), dtmin, pval = TRUE, pval.coord = c(150, 0.10), pval.size = 4) + ggtitle("Survival by Confirmed SIRS") + xlab("Time (months)")
ggsave("figures/sirs.png")
ggsurvplot(survfit(se ~ comp, dtmin), dtmin, pval = TRUE, pval.coord = c(150, 0.10), pval.size = 4) + ggtitle("Survival given complications") + xlab("Time (months)")
ggsave("figures/complication.png")
ggsurvplot(survfit(se ~ joint, dtmin), dtmin, pval = TRUE, pval.coord = c(150, 0.10), pval.size = 4) + ggtitle("Survival by operated joint") + xlab("Time (months)")
ggsave("figures/joint.png")
ggsurvplot(survfit(se ~ stat.tja, dtmin), dtmin, pval = TRUE, pval.coord = c(150, 0.10), pval.size = 4) + ggtitle("Survival by success of TJA") + xlab("Time (months)")
ggsave("figures/status.png")
ggsurvplot(survfit(se ~ outcome, dtmin), dtmin, pval = TRUE, pval.coord = c(150, 0.10), pval.size = 4) + ggtitle("Survival by surgery outcome") + xlab("Time (months)")
ggsave("figures/result.png")
ggsurvplot(survfit(se ~ comp.type, dtmin), dtmin, pval = TRUE, pval.coord = c(150, 0.10), pval.size = 4) + ggtitle("Survival by type of complication") + xlab("Time (months)")
ggsave("figures/type.png")
